config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"

    get "/logout", to: "sessions#destroy"

    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts, only: [:index, :show, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :groups, only: [:index, :show, :create, :destroy]
    resources :group_users, only: [:create]
    resources :comments, only: [:create, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".the_form_contains" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render "shared/error_messages", object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: t(".placeholder") %>
    </div>
    <span class="image">
      <%= f.file_field :image, :class => "btn btn-primary", :onChange => "readURL(this);", accept:  Settings.shared.micropost_form.image_path %>
    </span>
    <div id="file-upload-content">
      <img id="file-upload-image" src="#" />
    </div>
  <%= f.submit t(".btn_submit_post"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to following_user_path(@user) do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t ".title_link_following" %>
  <% end %>
  <%= link_to followers_user_path(@user) do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t ".title_link_follower" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: Settings.user.size.max_length), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t(".title_link"), current_user %></span>
<span><%= pluralize current_user.microposts.count, t(".txt_micropost") %></span>
<span><%= current_user.group %></span>