config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/home", to: "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"

    get "/logout", to: "sessions#destroy"

    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts, only: [:index, :show, :create, :destroy]
    resources :relationships, only: [:create, :destroy]
    resources :groups, only: [:index, :show, :create, :destroy]
    resources :group_users, only: [:create]
    resources :comments, only: [:create, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t ".the" %> <%= link_to t("web_rails"), Settings.href.rails %> <%= t ".by" %> <%= link_to t("author"), Settings.href.michaelhartl %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %></li>
      <li><%= link_to t(".contact"), contact_path %></li>
      <li><%= link_to t(".news"), Settings.href.rails_news %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("lack_name_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li>
            <%= search_form_for @q do |f| %>
              <% if path_link == root_path || @user && path_link == "/en/users/#{@user.id}" || path_link == microposts_path %>
                <%= f.search_field :content_cont %>
              <% else %>
                <%= f.search_field :name_cont %>
              <% end %>
              <%= f.submit :class => "btn btn-primary" %>
            <% end %>
          </li>
        <% end %>
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), help_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to t(".users"), users_path %></li>
          <% end %>
          <li><%= link_to t(".groups"), groups_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
              <%= t ".account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if It IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media:"all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <%= javascript_include_tag "custom" %>
  </body>
</html>